# Generated by Django 3.2.13 on 2022-06-10 15:46

from django.db import migrations, models

import taskrqe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RQE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefa', models.FloatField(validators=[taskrqe.models.validate_zero], verbose_name='A')),
                ('coefb', models.FloatField(verbose_name='B')),
                ('coefc', models.FloatField(verbose_name='C')),
                ('root1', models.FloatField(default=None, null=True, verbose_name='Корень 1')),
                ('root2', models.FloatField(default=None, null=True, verbose_name='Корень 2')),
            ],
            options={
                'verbose_name': 'Коэффициент квадратичного уравнения',
                'verbose_name_plural': 'Коэффициенты квадратичного уравнения',
                'ordering': ('coefa',),
            },
        ),
    ]
