# Generated by Django 3.2.13 on 2022-06-11 16:34

from django.db import migrations, models

import taskitems.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('RED', 'Красный'), ('GREEN', 'Зеленый'), ('BLUE', 'Синий')], default=None, max_length=256, null=True, verbose_name='Цвет предмета')),
                ('number', models.PositiveIntegerField(unique=True, validators=[taskitems.models.validate_zero], verbose_name='Номер предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ('number',),
            },
        ),
    ]
